# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
    default:
        desc: build
        cmds:
            - go build -trimpath -ldflags '-s -w -H=windowsgui' -o cmd/creator/win-webapp-loader.exe ./cmd/loader/
            # - go build -trimpath -ldflags '-s -w' -o cmd/creator/win-webapp-loader.exe ./cmd/loader2/
            - go build -trimpath -ldflags '-s -w' -o bin/win-webapp-gen.exe ./cmd/creator/
            - rm cmd/creator/win-webapp-loader.exe
            - cp bin/win-webapp-gen.exe D:/Users/bin/win-webapp-gen.exe
