# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
    default:
        desc: build
        cmds:
            - go build -trimpath -ldflags '-s -w -H=windowsgui' -o win-webapp-loader.exe
            - go build -trimpath -ldflags '-s -w' -tags creator -o bin/win-webapp-gen.exe
            - rm win-webapp-loader.exe
            - cp bin/win-webapp-gen.exe D:/Users/bin/win-webapp-gen.exe
